// Code generated by gen-config.
// data/app.tml
// data/dev/api.tml
// data/dev/database.tml
// data/dev/view.tml
// data/test/api.tml
// data/test/database.tml
// data/test/view.tml
// DO NOT EDIT

package config

import (
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/gophergala2016/source/core/foundation"
)

type (
	App struct {
		Name   string `toml:"name"`
		Secret string `toml:"secret"`
	}
	API struct {
		Token string `toml:"token"`
	}
	Database struct {
		Driver string `toml:"driver"`
		Source string `toml:"source"`
	}
	View struct {
		Template struct {
			Delimiters string `toml:"delimiters"`
		}
	}

	ConfigData struct {
		Mode string

		App      App      `toml:"app"`
		API      API      `toml:"api"`
		Database Database `toml:"database"`
		View     View     `toml:"view"`
	}
)

const configDir = "data"

var config ConfigData = ConfigData{}

func init() {
	Load()
}

func Get() ConfigData {
	return config
}

func Load() {
	mode := foundation.Mode()
	names := []string{
		"app.tml",
		"dev/api.tml",
		"dev/database.tml",
		"dev/view.tml",
		"test/api.tml",
		"test/database.tml",
		"test/view.tml",
	}
	for _, name := range names {
		dir, _ := filepath.Split(name)
		if len(dir) > 0 && !strings.HasPrefix(dir, mode) {
			continue
		}
		b := MustAsset(filepath.Join(configDir, name))
		err := config.Unmarshal(b)
		if err != nil {
			panic(err)
		}
		foundation.Printf("Load Config File: %s", name)
	}
	config.Mode = mode
}

func (c *ConfigData) Unmarshal(b []byte) error {
	return toml.Unmarshal(b, c)
}

func GetApp() App {
	return Get().App
}

func GetAPI() API {
	return Get().API
}

func GetDatabase() Database {
	return Get().Database
}

func GetView() View {
	return Get().View
}
