INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Mercury','#ff2b2b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('TypeScript','#2b7489', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PureBasic','#5a6986', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Objective-C++','#6866fb', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Self','#0579aa', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('edn','#db5855', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('NewLisp','#87AED7', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Jupyter Notebook','#DA5B0B', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Rebol','#358a5b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Frege','#00cafe', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Dart','#00B4AB', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('AspectJ','#a957b0', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Shell','#89e051', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Web Ontology Language','#9cc9dd', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('xBase','#403a40', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Eiffel','#946d57', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Nix','#7e7eff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('RAML','#77d9fb', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('MTML','#b7e1f4', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Racket','#22228f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Elixir','#6e4a7e', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SAS','#B34936', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Agda','#315665', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('wisp','#7582D1', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('D','#ba595e', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Kotlin','#F18E33', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Opal','#f7ede0', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Crystal','#776791', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Objective-C','#438eff', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ColdFusion CFC','#ed2cd6', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Oz','#fab738', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Mirah','#c7a938', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Objective-J','#ff0c5a', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Gosu','#82937f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('FreeMarker','#0050b2', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Ruby','#701516', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Component Pascal','#b0ce4e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Arc','#aa2afe', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Brainfuck','#2F2530', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Nit','#009917', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('APL','#5A8164', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Go','#375eab', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Visual Basic','#945db7', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PHP','#4F5D95', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Cirru','#ccccff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SQF','#3F3F3F', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Glyph','#e4cc98', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Java','#b07219', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('MAXScript','#00a6a6', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Scala','#DC322F', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Makefile','#427819', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ColdFusion','#ed2cd6', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Perl','#0298c3', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Lua','#000080', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Vue','#2c3e50', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Verilog','#b2b7f8', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Factor','#636746', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Haxe','#df7900', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Pure Data','#91de79', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Forth','#341708', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Red','#ee0000', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Hy','#7790B2', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Volt','#1F1F1F', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('LSL','#3d9970', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('eC','#913960', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('CoffeeScript','#244776', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('HTML','#e44b23', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Lex','#DBCA00', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('API Blueprint','#2ACCA8', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Swift','#ffac45', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('C','#555555', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('AutoHotkey','#6594b9', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Isabelle','#FEFE00', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Metal','#8f14e9', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Clarion','#db901e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('JSONiq','#40d47e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Boo','#d4bec1', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('AutoIt','#1C3552', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Clojure','#db5855', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Rust','#dea584', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Prolog','#74283c', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SourcePawn','#5c7611', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('AMPL','#E6EFBB', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('FORTRAN','#4d41b1', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ANTLR','#9DC3FF', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Harbour','#0e60e3', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Tcl','#e4cc98', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('BlitzMax','#cd6400', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PigLatin','#fcd7de', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Lasso','#999999', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ECL','#8a1267', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('VHDL','#adb2cb', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Elm','#60B5CC', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Propeller Spin','#7fa2a7', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('X10','#4B6BEF', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('IDL','#a3522f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ATS','#1ac620', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Ada','#02f88c', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Unity3D Asset','#ab69a1', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Nu','#c9df40', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('LFE','#004200', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SuperCollider','#46390b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Oxygene','#cdd0e3', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ASP','#6a40fd', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Assembly','#6E4C13', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Gnuplot','#f0a9f0', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('JFlex','#DBCA00', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('NetLinx','#0aa0ff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Turing','#45f715', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Vala','#fbe5cd', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Processing','#0096D8', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Arduino','#bd79d1', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('FLUX','#88ccff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('NetLogo','#ff6375', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('C Sharp','#178600', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('CSS','#563d7c', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Emacs Lisp','#c065db', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Stan','#b2011d', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SaltStack','#646464', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('QML','#44a51c', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Pike','#005390', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('LOLCODE','#cc9900', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ooc','#b0b77e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Handlebars','#01a9d6', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('J','#9EEDFF', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Mask','#f97732', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('EmberScript','#FFF4F3', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('TeX','#3D6117', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Nemerle','#3d3c6e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('KRL','#28431f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Ren Py','#ff7f7f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Unified Parallel C','#4e3617', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Golo','#88562A', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Fancy','#7b9db4', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('OCaml','#3be133', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Shen','#120F14', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Pascal','#b0ce4e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('F#','#b845fc', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Puppet','#302B6D', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ActionScript','#882B0F', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Diff','#88dddd', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Ragel in Ruby Host','#9d5200', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Fantom','#dbded5', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Zephir','#118f9e', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Click','#E4E6F3', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Smalltalk','#596706', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('DM','#447265', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Ioke','#078193', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PogoScript','#d80074', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('LiveScript','#499886', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('JavaScript','#f1e05a', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('VimL','#199f4b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PureScript','#1D222D', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('ABAP','#E8274B', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Matlab','#bb92ac', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Slash','#007eff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('R','#198ce7', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Erlang','#B83998', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Pan','#cc0000', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('LookML','#652B81', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Eagle','#814C05', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Scheme','#1e4aec', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PLSQL','#dad8d8', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Python','#3572A5', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Max','#c4a79c', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Common Lisp','#3fb68b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Latte','#A8FF97', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('XQuery','#5232e7', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Omgrofl','#cabbff', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('XC','#99DA07', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Nimrod','#37775b', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('SystemVerilog','#DAE1C2', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Chapel','#8dc63f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Groovy','#e69f56', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Dylan','#6c616e', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('E','#ccce35', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Parrot','#f3ca0a', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Grammatical Framework','#79aa7a', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Game Maker Language','#8fb200', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Papyrus','#6600cc', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('NetLinx+ERB','#747faa', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Clean','#3F85AF', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Alloy','#64C800', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Squirrel','#800000', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('PAWN','#dbb284', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('UnrealScript','#a54c4d', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Standard ML','#dc566d', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Slim','#ff8f77', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Perl6','#0000fb', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Julia','#a270ba', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Haskell','#29b544', 1, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('NCL','#28431f', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Io','#a9188d', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Rouge','#cc0088', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('C++','#f34b7d', 2, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('AGS Script','#B9D9FF', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('Dogescript','#cca760', 0, now(), now());
INSERT INTO tag (name,color,score,created_at,updated_at) VALUES('nesC','#94B0C7', 0, now(), now());
