// Code generated by gen-routes.
// routes/api_v1.tml
// routes/routes.tml
// routes/web.tml
// DO NOT EDIT

package main

import (
	"github.com/gin-gonic/gin"

	"github.com/gophergala2016/source/core/foundation"
	"github.com/gophergala2016/source/core/net/context/accessor"

	"github.com/gophergala2016/source/internal/controllers/api"
	"github.com/gophergala2016/source/internal/controllers/web"
)

func router() *foundation.Engine {
	router := foundation.Default()

	// GET /v1/user/:id
	// api.APIUserController.GetUser
	router.GET("/v1/user/:id", func(c *gin.Context) {
		controller := &api.APIUserController{}
		ctx := foundation.NewContext(c)
		accessor.SetAction(ctx, "APIUserController.GetUser")
		controller.SetContext(ctx)
		controller.GetUser(c.Param("id"))
	})

	// GET /login
	// web.WebLoginController.Login
	router.GET("/login", func(c *gin.Context) {
		controller := &web.WebLoginController{}
		ctx := foundation.NewContext(c)
		accessor.SetAction(ctx, "WebLoginController.Login")
		controller.SetContext(ctx)
		controller.Login()
	})

	return router
}
