require 'rubygems'
require 'bundler/setup'
require 'prmd/rake_tasks/combine'
require 'prmd/rake_tasks/verify'
require 'prmd/rake_tasks/doc'
require 'prmd/link'
require 'redcarpet'
require 'systemu'

namespace :api do
  Prmd::RakeTasks::Combine.new do |t|
    t.options[:meta] = 'meta.json'
    t.paths << 'schemata'
    t.output_file = 'api.json'
  end

  Prmd::RakeTasks::Verify.new do |t|
    t.files << 'api.json'
  end

  Prmd::RakeTasks::Doc.new do |t|
    t.files = { 'api.json' => 'api.md' }
  end

  task :html do
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
    html = <<HTML
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
HTML
    html += markdown.render(File.read('api.md'))
    html += '</body></html>'
    File.write("api.html", html)
  end
end

task default: [:api]
task api: ['api:combine', 'api:verify', 'api:doc', 'api:html']
